<a href="https://colab.research.google.com/github/saad-ameer/Python-for-Data-Analyst/blob/main/challenge_questions_tfl_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Challenge Questions - TfL Dataset

# Instructions:
• Please ensure you don't overwrite any existing cells. Add new cells below by pressing ALT+ENTER

• Attempt all of the questions

• You are encouraged to look online for help should you need it

# Dataset overview:
There are three datasets stored in the same directory as this Notebook, they are all related to each other:

• **tfl-daily-cycle-hires.csv**: This dataset contains bike hire data from Transport for London during the period
30th July 2010 to 30th September 2021. 'Day' is the day in '%d/%m/%Y' format. 'Number of Bicycle Hires' is the total number of bikes hired that day.

#

## Import pandas, numpy and datetime

In [7]:
import pandas as pd
import numpy as np
import datetime as dt

## Load the files:
• "tfl-daily-cycle-hires.csv" should be assigned to the variable **tfl**

In [8]:
tfl = pd.read_csv('tfl-daily-cycle-hires.csv')

## Check the head of the DataFrame

In [9]:
tfl.head()

          Day  Number of Bicycle Hires  Unnamed: 2
0  30/07/2010                   6897.0         NaN
1  31/07/2010                   5564.0         NaN
2  01/08/2010                   4303.0         NaN
3  02/08/2010                   6642.0         NaN
4  03/08/2010                   7966.0         NaN

## Check the data types of the DataFrame columns

In [10]:
tfl.dtypes

Day                         object
Number of Bicycle Hires    float64
Unnamed: 2                 float64
dtype: object

## Change the data types and remove unnecessary columns

• 'Day' should be a datetime64 data type

• 'Number of Bicycle Hires' should be float64

• Any other columns should be deleted

In [11]:
#tfl['Day'] = tfl['Day'].astype('datetime64[ns]')
tfl['Day'] = pd.to_datetime(tfl['Day'],format='%d/%m/%Y')

In [12]:
tfl = tfl.drop(columns=['Unnamed: 2'])
#tfl.drop(columns='Unnmaed: 2', inplace=True)

## What is the average number of bicycle hires per day across the entire dataset?

In [13]:
tfl.describe()

                       Day  Number of Bicycle Hires
count                 4081              4081.000000
mean   2016-02-29 00:00:00             26261.932124
min    2010-07-30 00:00:00              2764.000000
25%    2013-05-15 00:00:00             19201.000000
50%    2016-02-29 00:00:00             26030.000000
75%    2018-12-15 00:00:00             33313.000000
max    2021-09-30 00:00:00             73094.000000
std                    NaN              9741.300803

In [14]:
tfl['Number of Bicycle Hires'].mean()

np.float64(26261.932124479295)

In [15]:
tfl.groupby('Day')['Number of Bicycle Hires'].mean()

Day
2010-07-30     6897.0
2010-07-31     5564.0
2010-08-01     4303.0
2010-08-02     6642.0
2010-08-03     7966.0
               ...
2021-09-26    45120.0
2021-09-27    32167.0
2021-09-28    32539.0
2021-09-29    39889.0
2021-09-30    34070.0
Name: Number of Bicycle Hires, Length: 4081, dtype: float64

## Create a new column called 'Year' which contains the 4 digit year

In [16]:
#tfl['Year'] = tfl['Day'].dt.year
tfl['Year'] = tfl['Day'].dt.strftime('%Y')

In [17]:
tfl

            Day  Number of Bicycle Hires  Year
0    2010-07-30                   6897.0  2010
1    2010-07-31                   5564.0  2010
2    2010-08-01                   4303.0  2010
3    2010-08-02                   6642.0  2010
4    2010-08-03                   7966.0  2010
...         ...                      ...   ...
4076 2021-09-26                  45120.0  2021
4077 2021-09-27                  32167.0  2021
4078 2021-09-28                  32539.0  2021
4079 2021-09-29                  39889.0  2021
4080 2021-09-30                  34070.0  2021

[4081 rows x 3 columns]

## What is the average number of bicycle hires per Year across the entire dataset

In [18]:
tfl.groupby('Year')['Number of Bicycle Hires'].mean()

Year
2010    14069.761290
2011    19568.353425
2012    26008.969945
2013    22042.353425
2014    27462.731507
2015    27046.134247
2016    28152.013661
2017    28619.298630
2018    28952.164384
2019    28561.520548
2020    28508.653005
2021    30091.069597
Name: Number of Bicycle Hires, dtype: float64

In [19]:
tfl.pivot_table(index='Year',aggfunc='mean',values='Number of Bicycle Hires')

      Number of Bicycle Hires
Year
2010             14069.761290
2011             19568.353425
2012             26008.969945
2013             22042.353425
2014             27462.731507
2015             27046.134247
2016             28152.013661
2017             28619.298630
2018             28952.164384
2019             28561.520548
2020             28508.653005
2021             30091.069597

## What is the total number of bicycle hires per Year across the entire dataset

In [20]:
tfl.groupby('Year')['Number of Bicycle Hires'].sum()

Year
2010     2180813.0
2011     7142449.0
2012     9519283.0
2013     8045459.0
2014    10023897.0
2015     9871839.0
2016    10303637.0
2017    10446044.0
2018    10567540.0
2019    10424955.0
2020    10434167.0
2021     8214862.0
Name: Number of Bicycle Hires, dtype: float64

## Create a new column called 'Category' on the tfl DataFrame that classifies the number of bike hires per day as:
* 'Low' if the 'Number of Bicycle Hires' is below 10,000
* 'Medium' if the 'Number of Bicycle Hires' is below 40,000 but greater than or equal to 10,000
* 'High' if the 'Number of Bicycle Hires' is greater than or equal to 40,000

In [21]:
tfl['Category'] = np.where(tfl['Number of Bicycle Hires'] < 10000, 'Low',
                           np.where(tfl['Number of Bicycle Hires'] < 40000, 'Medium', 'High'))

In [22]:
tfl

            Day  Number of Bicycle Hires  Year Category
0    2010-07-30                   6897.0  2010      Low
1    2010-07-31                   5564.0  2010      Low
2    2010-08-01                   4303.0  2010      Low
3    2010-08-02                   6642.0  2010      Low
4    2010-08-03                   7966.0  2010      Low
...         ...                      ...   ...      ...
4076 2021-09-26                  45120.0  2021     High
4077 2021-09-27                  32167.0  2021   Medium
4078 2021-09-28                  32539.0  2021   Medium
4079 2021-09-29                  39889.0  2021   Medium
4080 2021-09-30                  34070.0  2021   Medium

[4081 rows x 4 columns]

In [23]:
def classify(x):
  if x>=40000:
    return 'High'
  elif x>=10000:
    return 'Medium'
  else:
    return 'Low'

In [24]:
tfl['Category'] = tfl['Number of Bicycle Hires'].apply(classify)

In [30]:
tfl.head(15)

          Day  Number of Bicycle Hires  Year Category
0  2010-07-30                   6897.0  2010      Low
1  2010-07-31                   5564.0  2010      Low
2  2010-08-01                   4303.0  2010      Low
3  2010-08-02                   6642.0  2010      Low
4  2010-08-03                   7966.0  2010      Low
5  2010-08-04                   7893.0  2010      Low
6  2010-08-05                   8724.0  2010      Low
7  2010-08-06                   9797.0  2010      Low
8  2010-08-07                   6631.0  2010      Low
9  2010-08-08                   7864.0  2010      Low
10 2010-08-09                   6191.0  2010      Low
11 2010-08-10                   4802.0  2010      Low
12 2010-08-11                  14013.0  2010   Medium
13 2010-08-12                  13080.0  2010   Medium
14 2010-08-13                  12151.0  2010   Medium

## For each year in the tfl DataFrame how many days are classed as 'Low', 'Medium' or 'High'?

In [25]:
tfl.groupby(['Year','Category']).size()

Year  Category
2010  Low          44
      Medium      111
2011  Low          30
      Medium      335
2012  High         27
      Low          19
      Medium      320
2013  Low          25
      Medium      340
2014  High         27
      Low          10
      Medium      328
2015  High         12
      Low           9
      Medium      344
2016  High         37
      Low           6
      Medium      323
2017  High         28
      Low          13
      Medium      324
2018  High         52
      Low          16
      Medium      297
2019  High         20
      Low           3
      Medium      342
2020  High         63
      Low          11
      Medium      292
2021  High         62
      Low           9
      Medium      202
dtype: int64

In [26]:
tfl.groupby(by=['Year','Category']).count()

               Day  Number of Bicycle Hires
Year Category
2010 Low        44                       44
     Medium    111                      111
2011 Low        30                       30
     Medium    335                      335
2012 High       27                       27
     Low        19                       19
     Medium    320                      320
2013 Low        25                       25
     Medium    340                      340
2014 High       27                       27
     Low        10                       10
     Medium    328                      328
2015 High       12                       12
     Low         9                        9
     Medium    344                      344
2016 High       37                       37
     Low         6                        6
     Medium    323                      323
2017 High       28                       28
     Low        13                       13
     Medium    324                      324
2018 High       52                       52
     Low        16                       16
     Medium    297                      297
2019 High       20                       20
     Low         3                        3
     Medium    342                      342
2020 High       63                       63
     Low        11                       11
     Medium    292                      292
2021 High       62                       62
     Low         9                        9
     Medium    202                      202